# This workflow will test the python application

name: Python test
on: [push, pull_request]

jobs:
  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.11.16

    steps:
    - uses: actions/checkout@v3
    - name: Install python version
      uses: gabrielfalcao/pyenv-action@v11
      with:
        default: "${{ matrix.python }}"
        command: pyenv update
        #command: pip install -U pip  # upgrade pip after installing python

    - name: Run tests
      run: make test
